# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20160221_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
